//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/action/rats.html
halflife.wad
liquids.wad
xeno.wad
decals.wad
cached.wad
gfx.wad
sound/ambience/steamjet1.wav
sound/apache/ap_rotor3.wav
maps/rats.bsp
gfx/env/duskbk.tga
gfx/env/duskdn.tga
gfx/env/duskft.tga
gfx/env/dusklf.tga
gfx/env/duskrt.tga
gfx/env/duskup.tga
