//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/2000_2_frozen.html
halflife.wad
sprites/fire.spr
sound/ambience/industrial1.wav
gfx/env/xmasbk.tga
gfx/env/xmasdn.tga
gfx/env/xmasft.tga
gfx/env/xmaslf.tga
gfx/env/xmasrt.tga
gfx/env/xmasup.tga
maps/2000_2_frozen.bsp
