//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/dutch_wintersport.html
sprites/glow01.spr
sound/ambience/breather.wav
sound/ambience/boomer.wav
gfx/env/iceflow256_bk.tga
gfx/env/iceflow256_dn.tga
gfx/env/iceflow256_ft.tga
gfx/env/iceflow256_lf.tga
gfx/env/iceflow256_rt.tga
gfx/env/iceflow256_up.tga
models/dutch/snow/snowtree01.mdl
models/dutch/xen_plant8.mdl
maps/dutch_wintersport.bsp
