//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/tig_qui.html
halflife.wad
decals.wad
liquids.wad
xeno.wad
sprites/glow01.spr
gfx/env/duskbk.tga
gfx/env/duskdn.tga
gfx/env/duskft.tga
gfx/env/dusklf.tga
gfx/env/duskrt.tga
gfx/env/duskup.tga
sound/ambience/bee1.wav
sound/ambience/bee2.wav
maps/tig_qui.bsp
