name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the base image
      run: docker build -t unixs/steam:base -f docker/base.dockerfile docker/hlds
#    - name: Build the private image
#      run: docker build -t unixs/steam:private -f docker/private.dockerfile docker/hlds
