name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_cmd:
    runs-on: ubuntu-latest
    name: Docker image SteamCMD

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push base image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: docker/cmd
        file: docker/cmd.dockerfile
        push: true
        tags: unixs/steam:cmd
        # labels: ${{ steps.meta.outputs.labels }}


  build_l4d2:
    needs: build_cmd
    runs-on: ubuntu-latest
    name: Docker image Left 4 Dead 2

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push l4d2 image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: docker/l4d2
        file: docker/l4d2.dockerfile
        push: true
        tags: unixs/steam:l4d2
        # labels: ${{ steps.meta.outputs.labels }}


  build_valve:
    needs: build_cmd
    runs-on: ubuntu-latest
    name: Docker image Half-Life server base

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Half-Life server base image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: docker/valve
        file: docker/valve.dockerfile
        push: true
        tags: unixs/steam:valve
        # labels: ${{ steps.meta.outputs.labels }}


  build_valve_mods:
    needs: build_valve
    runs-on: ubuntu-latest
    name: Docker image ${{ matrix.mod }}
    strategy:
      matrix:
        mod: [private, open, rats, private-hltv]

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push ${{ matrix.mod }} image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: docker/valve
        file: docker/${{ matrix.mod }}.dockerfile
        push: true
        tags: unixs/steam:${{ matrix.mod }}
        # labels: ${{ steps.meta.outputs.labels }}


  deploy:
    needs:
      - build_valve_mods
      - build_l4d2
    runs-on: ubuntu-latest
    name: Deploy servers
    steps:
      - uses: actions/checkout@v3
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa-github-actions
          known_hosts: somethingrandom
          config: |
            Host games
              HostName ${{ secrets.HOST }}
              User ${{ secrets.SSH_USER }}
              IdentityFile ~/.ssh/id_rsa-github-actions
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - name: Copy deploy script
        run: scp deploy.sh games:hl/deploy.sh
      - name: Exec script
        run: ssh games ./hl/deploy.sh
