name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_base:

    runs-on: ubuntu-latest
    name: Docker image base

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push base image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: docker/hlds
        file: docker/base.dockerfile
        push: true
        tags: unixs/steam:base
        # labels: ${{ steps.meta.outputs.labels }}


  build_mods:
    needs: build_base
    runs-on: ubuntu-latest
    name: Docker image ${{ matrix.mod }}
    strategy:
      matrix:
        mod: [private, open, rats, private-hltv]

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push ${{ matrix.mod }} image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: docker/hlds
        file: docker/${{ matrix.mod }}.dockerfile
        push: true
        tags: unixs/steam:${{ matrix.mod }}
        # labels: ${{ steps.meta.outputs.labels }}


  deploy:
    needs: build_mods
    runs-on: ubuntu-latest
    name: Deploy servers
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa-github-actions
          known_hosts: somethingrandom
          config: |
            Host games
              HostName ${{ secrets.HOST }}
              User ${{ secrets.SSH_USER }}
              IdentityFile ~/.ssh/id_rsa-github-actions
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - name: Exec script
        run: |
          ssh games cd hl &&\
          docker compose ls &&\
          docker compose -f servers.yml pull &&\
          docker compose -f servers.yml stop &&\
          docker compose -f servers.yml rm &&\
          docker compose -f servers.yml up -d
