name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    name: Docker image ${{ matrix.mod }}
    strategy:
      matrix:
        mod: [base, private, open, rats, private-hltv]

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push ${{ matrix.mod }} image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: docker/hlds
        file: docker/${{ matrix.mod }}.dockerfile
        push: true
        tags: unixs/steam:${{ matrix.mod }}
        # labels: ${{ steps.meta.outputs.labels }}
